# Generated by Django 4.2 on 2023-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_number', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('meat_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('serving_quantity', models.IntegerField()),
                ('serve', models.CharField(blank=True, max_length=100, null=True)),
                ('meal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cookware', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_per_serving', models.IntegerField()),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('ingredients_unit_of_measure', models.JSONField(blank=True, null=True)),
                ('steps', models.JSONField(blank=True, null=True)),
                ('tips', models.JSONField(blank=True, null=True)),
                ('time_duration_in_minutes', models.JSONField(blank=True, null=True)),
                ('nutrients_info', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
