# Generated by Django 4.2 on 2023-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.CharField(blank=True, max_length=255, null=True)),
                ('alternate', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='ingredients_unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='nutrients_info',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='time_duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='tips',
        ),
    ]
