# Generated by Django 4.2 on 2023-04-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_menu_calories_per_serving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='menu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.menu'),
            preserve_default=False,
        ),
    ]
