# Generated by Django 4.2 on 2023-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menu_actual_menu_alternate_menu_bowl_menu_bunch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='actual',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
