# Generated by Django 4.2 on 2023-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_menu_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
