from django.db import models

# Create your models here.

from django.db import models

class Menu (models.Model):
    pdf_number = models.CharField(max_length=255, null=True, blank=True)
    recipe_name = models.CharField(max_length=255, null=True, blank=True)
    alternate_name = models.CharField(max_length=255, null=True, blank=True)
    recipe_type = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    meat_type = models.CharField(max_length=255, null=True, blank=True)
    meat_classification = models.CharField(max_length=255, null=True, blank=True)
    cuisine = models.CharField(max_length=255, null=True, blank=True)
    serving_quantity = models.CharField(max_length=255, null=True, blank=True)
    serve = models.CharField(max_length=255, null=True, blank=True)
    meal_type = models.CharField(max_length=255, null=True, blank=True)
    cookware = models.CharField(max_length=255, null=True, blank=True)
    calories_per_serving = models.CharField(max_length=255, null=True, blank=True)
    actual = models.CharField(max_length=255, blank=True,null=True)
    alternate = models.CharField(max_length=255, null=True, blank=True)
    comments = models.CharField(max_length=255, null=True, blank=True)
    oz = models.CharField(max_length=255, null=True, blank=True)
    ml = models.CharField(max_length=255, null=True, blank=True)
    pound = models.CharField(max_length=255, null=True, blank=True)
    kg = models.CharField(max_length=255, null=True, blank=True)
    gm = models.CharField(max_length=255,blank=True, null=True)
    cubes = models.CharField(max_length=255,blank=True, null=True)
    pints = models.CharField(max_length=255,blank=True, null=True)
    tbsp = models.CharField(max_length=255,blank=True, null=True)
    lb = models.CharField(max_length=255,blank=True, null=True)
    tsp = models.CharField(max_length=255,blank=True, null=True)
    cm = models.CharField(max_length=255,blank=True, null=True)
    cups = models.CharField(max_length=255,blank=True, null=True)
    inch = models.CharField(max_length=255,blank=True, null=True)
    bowl = models.CharField(max_length=255,blank=True, null=True)
    pinch = models.CharField(max_length=255,blank=True, null=True)
    litres = models.CharField(max_length=255,blank=True, null=True)
    count = models.CharField(max_length=255,blank=True, null=True)
    cakes = models.CharField(max_length=255,blank=True, null=True)
    piece = models.CharField(max_length=255,blank=True, null=True)
    squares = models.CharField(max_length=255,blank=True, null=True)
    stalks = models.CharField(max_length=255,blank=True, null=True)
    variation_alternate = models.CharField(max_length=255, blank=True)
    dsp = models.CharField(max_length=255,blank=True, null=True)
    slices = models.CharField(max_length=255,blank=True, null=True)
    flakes = models.CharField(max_length=255,blank=True, null=True)
    bunch = models.CharField(max_length=255,blank=True, null=True)
    cubes_2 = models.CharField(max_length=255,blank=True, null=True)
    whole_heads = models.CharField(max_length=255,blank=True, null=True)
    for_taste = models.CharField(max_length=255, blank=True)
    part = models.CharField(max_length=255, blank=True)
    heaped_tsp = models.CharField(max_length=255,blank=True, null=True)
    catty = models.CharField(max_length=255,blank=True, null=True)
    cooking = models.TextField(null=True,blank=True)
    pre_cooking = models.TextField(null=True,blank=True)
    cook_tip = models.TextField(blank=True)
    serve_tip = models.TextField(blank=True)
    others = models.TextField(blank=True)
    cook_time =models.CharField(max_length=255, blank=True)
    prep_time = models.CharField(max_length=255, blank=True)
    soak_time = models.CharField(max_length=255, blank=True)
    marinate_time = models.CharField(max_length=255, blank=True)
    total_time = models.CharField(max_length=255, blank=True)
    energy =models.CharField(max_length=255, blank=True)
    protein = models.CharField(max_length=255, blank=True)
    kcal = models.CharField(max_length=255, blank=True)
    cal = models.CharField(max_length=255, blank=True)
    carbohydrate = models.CharField(max_length=255, blank=True)
    sugars = models.CharField(max_length=255, null=True, blank=True)
